#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<i>Checking current version...</i>"
echo "<p>Your current build is: <p id='current'>$(cat current)</p></p>"
echo "<i>Checking version from server...</i>"
echo "<pre>$(wget https://raw.githubusercontent.com/mhognl/RaspTopOS/testing/latest -O /tmp/latest)</p>"
echo "<p>Version from server is: <p id='latest'>$(cat /tmp/latest)</p></p>"
echo "<script>"
echo "if (document.getElementById('current').innerHTML==document.getElementById('latest').innerHTML) {"
echo "document.write('<h1>Your system is up-to-date!</h1>');"
echo "}"
echo "else {"
echo "location.href='update-ui_latest.cgi';"
echo "}"
echo "</script>"